# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='link',
        ),
    ]
